### ISSUE TITLE
The option 'image gallery' is missing in Woocommerce. How come?

### ISSUE THREAD

**Issue by davidvb67** [wordpresstips/WooCommerce-Product-Gallery#1]
In my version of Woocommerce (incorporated in another theme) the 'image gallery' option is missing. What can I do about this?
![schermafbeelding 2017-10-10 om 21 12 44](https://user-images.githubusercontent.com/32685382/31406723-b16e1446-ae02-11e7-89bc-59829371413e.png)
![schermafbeelding 2017-10-10 om 21 26 44](https://user-images.githubusercontent.com/32685382/31406733-b959a24c-ae02-11e7-96c7-e9f3b12783fe.png)

**Comment by opensourcemadan** [comment]
@davidvb67 Image Gallery option is removed by WooCommerce after version 3.0.

If you are using new version of WooCommerce (3.0+), you need to add gallery features in your theme you must declare support using add_theme_support(). like
`add_action( 'after_setup_theme', 'yourtheme_setup' );
 
function yourtheme_setup() {
    add_theme_support( 'wc-product-gallery-zoom' );
    add_theme_support( 'wc-product-gallery-lightbox' );
    add_theme_support( 'wc-product-gallery-slider' );
}`

[Click here](https://woocommerce.wordpress.com/2017/02/28/adding-support-for-woocommerce-2-7s-new-gallery-feature-to-your-theme/) for more details

**Comment by davidvb67** [comment]
Thanks for helping me out.

Do I have to replace ‘yourtheme’ with the name of the theme I am using, in my case this is theme48893 (which is a sub theme of Cherry)?

**Comment by opensourcemadan** [comment]
"Yourtheme" indicates active theme folder you are using.
